export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const ADD_INITIAL_DATA = 'ADD_INITIAL_DATA'
export const REMOVE_PROJECT_FROM_STORE = 'REMOVE_PROJECT_FROM_STORE';
export const UPDATE_PROJECT_IN_STORE = 'UPDATE_PROJECT_IN_STORE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const LOG_IN = 'LOG_IN';